#!/usr/bin/env python3
"""Build RE7 RSZ Lua databases from rszre7rt.json and re3rt_enums.json."""

import json, os, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
RSZ_JSON = os.path.join(ROOT, "re7", "rszre7rt.json")
ENUM_JSON = os.path.join(ROOT, "re7", "re3rt_enums.json")
OUTPUT_DIR = os.path.join(ROOT, "re7", "requiem_trainer", "emv_engine")

INCLUDE_PREFIXES = ("app.", "via.", "anim.")
SKIP_PREFIXES = (
    "System.Collections.", "System.Array.", "System.Linq.",
    "System.Runtime.", "System.Threading.", "System.Reflection.",
    "System.Converter", "System.Func", "System.Action",
    "System.Predicate", "System.Comparison",
)


def lua_escape(s):
    return s.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n").replace("\r", "")


def build_types():
    print(f"Reading {RSZ_JSON}...")
    with open(RSZ_JSON, "r", encoding="utf-8") as f:
        data = json.load(f)

    types = {}
    for key, entry in data.items():
        if key == "metadata":
            continue
        name = entry.get("name", "")
        if not name:
            continue
        if not any(name.startswith(p) for p in INCLUDE_PREFIXES):
            continue
        if any(name.startswith(p) for p in SKIP_PREFIXES):
            continue
        if "`" in name or "<" in name:
            continue
        fields = entry.get("fields", [])
        if not fields:
            continue
        if len(fields) == 1 and fields[0].get("name") == "value__":
            continue
        parent = entry.get("parent", "")
        types[name] = {"parent": parent, "fields": fields}

    print(f"  Found {len(types)} types with fields (from {len(data)} total entries)")

    out_path = os.path.join(OUTPUT_DIR, "rsz_types.lua")
    print(f"Writing {out_path}...")

    lines = [
        "-- AUTO-GENERATED by tools/build_re7_db.py - DO NOT EDIT",
        f"-- {len(types)} RE7 types with field definitions",
        "-- Source: re7/rszre7rt.json",
        "return {",
    ]
    for name in sorted(types.keys()):
        t = types[name]
        ename = lua_escape(name)
        lines.append(f'["{ename}"] = {{')
        if t["parent"]:
            lines.append(f'  parent = "{lua_escape(t["parent"])}",')
        lines.append("  fields = {")
        for f in t["fields"]:
            fname = lua_escape(f.get("name", ""))
            ftype = f.get("type", "?")
            orig = lua_escape(f.get("original_type", ""))
            is_array = "true" if f.get("array", False) else "false"
            size = f.get("size", 0)
            lines.append(
                f'    {{name="{fname}", type="{ftype}", orig="{orig}", array={is_array}, size={size}}},'
            )
        lines.append("  },")
        lines.append("},")
    lines.append("}")

    with open(out_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    size_kb = os.path.getsize(out_path) / 1024
    print(f"  Written {size_kb:.0f} KB ({len(types)} types)")
    return len(types)


def build_enums():
    print(f"Reading {ENUM_JSON}...")
    with open(ENUM_JSON, "r", encoding="utf-8") as f:
        edata = json.load(f)

    enums = {}
    for name, values in edata.items():
        if not isinstance(values, list):
            continue
        if len(values) > 256:
            continue
        if not values:
            continue
        enums[name] = values

    print(f"  Found {len(enums)} enums (from {len(edata)} total)")

    out_path = os.path.join(OUTPUT_DIR, "rsz_enums.lua")
    print(f"Writing {out_path}...")

    lines = [
        "-- AUTO-GENERATED by tools/build_re7_db.py - DO NOT EDIT",
        f"-- {len(enums)} RE7 enum definitions",
        "-- Source: re7/re3rt_enums.json",
        "return {",
    ]
    for name in sorted(enums.keys()):
        values = enums[name]
        ename = lua_escape(name)
        lines.append(f'["{ename}"] = {{')
        for v in values:
            vname = lua_escape(v.get("name", "?"))
            vval = v.get("value", 0)
            lines.append(f'  [{vval}] = "{vname}",')
        lines.append("},")
    lines.append("}")

    with open(out_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    size_kb = os.path.getsize(out_path) / 1024
    print(f"  Written {size_kb:.0f} KB ({len(enums)} enums)")
    return len(enums)


if __name__ == "__main__":
    print("=" * 60)
    print("RE7 RSZ Database Preprocessor")
    print("=" * 60)

    if not os.path.exists(RSZ_JSON):
        print(f"ERROR: {RSZ_JSON} not found!")
        sys.exit(1)
    if not os.path.exists(ENUM_JSON):
        print(f"ERROR: {ENUM_JSON} not found!")
        sys.exit(1)

    os.makedirs(OUTPUT_DIR, exist_ok=True)

    n_types = build_types()
    print()
    n_enums = build_enums()

    print()
    print("=" * 60)
    print(f"Done! {n_types} types, {n_enums} enums")
    print("=" * 60)
